### ISSUE TITLE
Suggestion: Chimata Releasable Nation

### ISSUE THREAD

**Issue by r-FlanboysUnite** [Touhou-Universalis/tohouniv_updated#126]
Chimata releasable for Italian region, somewhere along Venice. To control all the trade of the mediterranian 

Suggestor: Zhasa

Note: This is not evaluated.

Note: This does conflict with a previous suggestion where someone suggested to make them an advisor.

**Comment by ComradeFlan** [comment]
Maaaaybe

**Comment by Zerou73** [comment]
Done
